org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.2

fabric_loader_version=0.19.3
fabric_loom_version=1.17-SNAPSHOT
fabric_api_version=0.153.0+26.2

neoforge_version=26.2.0.32-beta
neoforge_moddev_version=2.0.141

mod_version=26.0.2
mod_id=noflyzone
mod_name=No-Fly Zone
mod_group=cx.gid.minecraft
archives_base_name=noflyzone

minecraft_version_min=26
neoforge_version_min=26.1.2.76
